[package]
name = "fbihtax"
version = "0.1.0"
authors = ["Ensar Sarajčić <es.ensar@gmail.com>"]
edition = "2021"


[dependencies]
pdf_forms = "0.3.4"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
